# 효용함수

## 개요

투자자의 선호와 위험회피를 효용함수를 통해 설명한다.

## 학습 목표

- 기대효용의 의미를 이해한다.
- 위험회피와 확실성 등가를 설명한다.
- 포트폴리오 선택 문제와 효용함수의 연결을 이해한다.

## 효용 함수, 기대 효용, 확실성 등가

### 효용 함수의 도입

[2장 현대 포트폴리오 이론](../02-modern-portfolio-theory/index.qmd)에서 이성적인 투자자의 포트폴리오 선택 문제를 살펴보았다. 무위험자산이 존재하지 않는다면 이성적인 투자자들은 효율적 투자선 위에서 자신의 위험 선호도에 맞는 포트폴리오를 선택할 것이다. 무위험자산이 존재한다면 시장 포트폴리오와 무위험자산을 적절히 조합하여 자신의 위험 성향에 맞도록 선택할 것이다.

그렇다면 효율적 포트폴리오 중 하나를 선택하는 과정은 개개인의 위험 선호도와 맞물려 어떻게 이루어질까? 이 장에서는 개별 투자자들의 포트폴리오 선택을 보다 자세히 살펴보며, 이를 효용 함수(utility function)를 바탕으로 설명한다.

경제학에서 효용(utility)은 소비자가 재화나 서비스를 소비한 대가로 얻는 만족이나 즐거움을 나타낸다. 효용 함수는 일련의 재화와 서비스에 대한 소비자의 선호도를 측정한다.

이 단원에서 효용 함수는 온전히 금융 자산에 대한 선호도를 측정하는 데 활용되며, 이를 위해 수학적 내용을 최대한 간단하게 구성한다.

### 상트페테르부르크 역설

투자자는 위험자산의 가치를 단순히 미래 페이오프(payoff)의 기댓값만으로 평가하지 않는다. 스위스 수학자 Nicolaus Bernoulli는 1713년 상트페테르부르크 역설(St. Petersburg paradox)로 알려진 다음 문제를 제시했다.

> 이 게임의 참가자는 공정한 동전을 던져 앞면이 나오면 2 ducat을 받고, 뒷면이 나오면 돈을 받지 못한 채 게임이 종료된다. ducat은 중세부터 19세기까지 유럽에서 사용된 금화의 일종이다.
>
> 앞면이 나오면 계속해서 동전을 던진다. 연속으로 앞면이 나오면 상금은 두 배씩 늘어나고, 언제든 뒷면이 나오면 게임이 종료된다.
>
> 이 게임에 참가하기 위해 얼마를 지불할 것인가?

위 게임에서 얻는 총 상금을 $W$라고 하면, $W$는 확률변수이며 그 기댓값은 다음과 같이 무한대이다.

$$
\mathbb{E}[W]
=0.5\times 2+0.5^2\times 2^2+0.5^3\times 2^3+\cdots
=1+1+1+\cdots
=\infty
$$

하지만 이 게임의 기댓값이 무한하다고 해서 게임에 참가하기 위해 무한대에 가까운 돈을 참가비로 지불하려는 사람은 없을 것이다. 이처럼 어떤 자산의 미래 가치에 대한 기댓값은 그 자산을 구매할 때 고려하는 유일한 평가 요소가 아니다. 그렇다면 개별 투자자가 위험자산을 구입할 때 추가로 고려하는 요소는 무엇인가?

이를 이해하기 위해 효용 함수의 개념이 도입되었다. 마코위츠도 포트폴리오 선택에 관한 연구에서 개별 투자자의 최적 포트폴리오를 투자자의 위험 선호도를 나타내는 효용 함수의 개념으로 설명하였다.